// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 16.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITest_lagerking
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public partial class UIMap
    {
        
        /// <summary>
        /// NavnInput - Use 'NavnInputParams' to pass parameters into this method.
        /// </summary>
        public void NavnInput()
        {
            #region Variable Declarations
            WpfEdit uITbxIdEdit = this.UILagerkingWindow.UITbxIdEdit;
            #endregion

            // Type 'Cola' in 'tbxId' text box
            uITbxIdEdit.Text = this.NavnInputParams.UITbxIdEditText;
        }
        
        /// <summary>
        /// PrisInput - Use 'PrisInputParams' to pass parameters into this method.
        /// </summary>
        public void PrisInput()
        {
            #region Variable Declarations
            WpfEdit uITextBox2Edit = this.UILagerkingWindow.UITextBox2Edit;
            WpfEdit uITextBox3Edit = this.UILagerkingWindow.UITextBox3Edit;
            #endregion

            // Type '25' in 'textBox2' text box
            uITextBox2Edit.Text = this.PrisInputParams.UITextBox2EditText;

            // Click 'textBox3' text box
            Mouse.Click(uITextBox3Edit, new Point(114, 16));
        }
        
        /// <summary>
        /// AntalInput - Use 'AntalInputParams' to pass parameters into this method.
        /// </summary>
        public void AntalInput()
        {
            #region Variable Declarations
            WpfEdit uITextBox3Edit = this.UILagerkingWindow.UITextBox3Edit;
            WpfComboBox uIItemComboBox = this.UILagerkingWindow.UIItemComboBox;
            WpfWindow uILagerkingWindow = this.UILagerkingWindow;
            #endregion

            // Type '2' in 'textBox3' text box
            uITextBox3Edit.Text = this.AntalInputParams.UITextBox3EditText;

            // Click combo box
            Mouse.Click(uIItemComboBox, new Point(144, 13));

            // Click 'Lagerking' window
            Mouse.Click(uILagerkingWindow, new Point(454, 289));
        }
        
        /// <summary>
        /// AfdelingInput - Use 'AfdelingInputParams' to pass parameters into this method.
        /// </summary>
        public void AfdelingInput()
        {
            #region Variable Declarations
            WpfComboBox uIItemComboBox = this.UILagerkingWindow.UIItemComboBox;
            #endregion

            // Select 'D' in combo box
            uIItemComboBox.SelectedItem = this.AfdelingInputParams.UIItemComboBoxSelectedItem;
        }
        
        /// <summary>
        /// AssertListViewInputCorrect - Use 'AssertListViewInputCorrectExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertListViewInputCorrect()
        {
            #region Variable Declarations
            WpfListItem uILagerkingProduktIndeListItem = this.UILagerkingWindow.UILbxAgentsList.UILagerkingProduktIndeListItem;
            #endregion

            // Verify that the 'DisplayText' property of 'lagerking.ProduktIndex' list item equals 'lagerking.ProduktIndex'
            Assert.AreEqual(this.AssertListViewInputCorrectExpectedValues.UILagerkingProduktIndeListItemDisplayText, uILagerkingProduktIndeListItem.DisplayText);
        }
        
        /// <summary>
        /// AddBtnTest
        /// </summary>
        public void AddBtnTest()
        {
            #region Variable Declarations
            WpfButton uITilføjvareButton = this.UILagerkingWindow.UIItemToolBar.UITilføjvareButton;
            #endregion

            // Click 'Tilføj vare' button
            Mouse.Click(uITilføjvareButton, new Point(15, 17));
        }
        
        /// <summary>
        /// NavnFieldInput - Use 'NavnFieldInputParams' to pass parameters into this method.
        /// </summary>
        public void NavnFieldInput()
        {
            #region Variable Declarations
            WpfEdit uITbxIdEdit = this.UILagerkingWindow.UITbxIdEdit;
            #endregion

            // Type 'Cola' in 'tbxId' text box
            uITbxIdEdit.Text = this.NavnFieldInputParams.UITbxIdEditText;
        }
        
        /// <summary>
        /// PrisfFieldInput - Use 'PrisfFieldInputParams' to pass parameters into this method.
        /// </summary>
        public void PrisfFieldInput()
        {
            #region Variable Declarations
            WpfEdit uITextBox2Edit = this.UILagerkingWindow.UITextBox2Edit;
            #endregion

            // Type '15' in 'textBox2' text box
            uITextBox2Edit.Text = this.PrisfFieldInputParams.UITextBox2EditText;
        }
        
        /// <summary>
        /// AntalFieldInput - Use 'AntalFieldInputParams' to pass parameters into this method.
        /// </summary>
        public void AntalFieldInput()
        {
            #region Variable Declarations
            WpfEdit uITextBox3Edit = this.UILagerkingWindow.UITextBox3Edit;
            #endregion

            // Type '300' in 'textBox3' text box
            uITextBox3Edit.Text = this.AntalFieldInputParams.UITextBox3EditText;
        }
        
        /// <summary>
        /// AfdelingFieldInput - Use 'AfdelingFieldInputParams' to pass parameters into this method.
        /// </summary>
        public void AfdelingFieldInput()
        {
            #region Variable Declarations
            WpfComboBox uIItemComboBox = this.UILagerkingWindow.UIItemComboBox;
            #endregion

            // Select 'B' in combo box
            uIItemComboBox.SelectedItem = this.AfdelingFieldInputParams.UIItemComboBoxSelectedItem;
        }
        
        /// <summary>
        /// AssertMethod1 - Use 'AssertMethod1ExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod1()
        {
            #region Variable Declarations
            WpfListItem uILagerkingProduktIndeListItem = this.UILagerkingWindow.UILbxAgentsList.UILagerkingProduktIndeListItem;
            #endregion

            // Verify that the 'DisplayText' property of 'lagerking.ProduktIndex' list item equals 'lagerking.ProduktIndex'
            Assert.AreEqual(this.AssertMethod1ExpectedValues.UILagerkingProduktIndeListItemDisplayText, uILagerkingProduktIndeListItem.DisplayText);

            // Verify that the 'DisplayText' property of 'lagerking.ProduktIndex' list item equals 'lagerking.ProduktIndex'
            Assert.AreEqual(this.AssertMethod1ExpectedValues.UILagerkingProduktIndeListItemDisplayText1, uILagerkingProduktIndeListItem.DisplayText);
        }
        
        /// <summary>
        /// AssertNavnInput_True - Use 'AssertNavnInput_TrueExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertNavnInput_True()
        {
            #region Variable Declarations
            WpfEdit uITbxIdEdit = this.UILagerkingWindow.UITbxIdEdit;
            #endregion

            // Verify that the 'Text' property of 'tbxId' text box equals 'Cola'
            Assert.AreEqual(this.AssertNavnInput_TrueExpectedValues.UITbxIdEditText, uITbxIdEdit.Text);
        }
        
        /// <summary>
        /// Login_Input
        /// </summary>
        public void Login_Input()
        {
            #region Variable Declarations
            WpfButton uILoginButton = this.UILagerkingWindow.UILoginButton;
            #endregion

            // Click 'Login' button
            Mouse.Click(uILoginButton, new Point(37, 7));
        }
        
        /// <summary>
        /// AddBtn_Input
        /// </summary>
        public void AddBtn_Input()
        {
            #region Variable Declarations
            WpfButton uITilføjvareButton = this.UILagerkingWindow.UIItemToolBar.UITilføjvareButton;
            #endregion

            // Click 'Tilføj vare' button
            Mouse.Click(uITilføjvareButton, new Point(17, 20));
        }
        
        /// <summary>
        /// Navn_Input - Use 'Navn_InputParams' to pass parameters into this method.
        /// </summary>
        public void Navn_Input()
        {
            #region Variable Declarations
            WpfEdit uITbxIdEdit = this.UILagerkingWindow.UITbxIdEdit;
            WpfListItem uILagerkingProduktIndeListItem = this.UILagerkingWindow.UILbxAgentsList.UILagerkingProduktIndeListItem;
            #endregion

            // Type 'Honning' in 'tbxId' text box
            uITbxIdEdit.Text = this.Navn_InputParams.UITbxIdEditText;

            // Click 'lagerking.ProduktIndex' list item
            Mouse.Click(uILagerkingProduktIndeListItem, new Point(50, 16));
        }
        
        /// <summary>
        /// Pris_Input - Use 'Pris_InputParams' to pass parameters into this method.
        /// </summary>
        public void Pris_Input()
        {
            #region Variable Declarations
            WpfEdit uITextBox2Edit = this.UILagerkingWindow.UITextBox2Edit;
            #endregion

            // Type '26' in 'textBox2' text box
            uITextBox2Edit.Text = this.Pris_InputParams.UITextBox2EditText;
        }
        
        /// <summary>
        /// Antal_Input - Use 'Antal_InputParams' to pass parameters into this method.
        /// </summary>
        public void Antal_Input()
        {
            #region Variable Declarations
            WpfEdit uITextBox3Edit = this.UILagerkingWindow.UITextBox3Edit;
            #endregion

            // Type '340' in 'textBox3' text box
            uITextBox3Edit.Text = this.Antal_InputParams.UITextBox3EditText;
        }
        
        /// <summary>
        /// NavnFelt_Input - Use 'NavnFelt_InputParams' to pass parameters into this method.
        /// </summary>
        public void NavnFelt_Input()
        {
            #region Variable Declarations
            WpfEdit uITbxIdEdit = this.UILagerkingWindow.UITbxIdEdit;
            WpfListItem uILagerkingProduktIndeListItem = this.UILagerkingWindow.UILbxAgentsList.UILagerkingProduktIndeListItem;
            #endregion

            // Type 'Honning' in 'tbxId' text box
            uITbxIdEdit.Text = this.NavnFelt_InputParams.UITbxIdEditText;

            // Click 'lagerking.ProduktIndex' list item
            Mouse.Click(uILagerkingProduktIndeListItem, new Point(135, 13));
        }
        
        /// <summary>
        /// Prisfelt_Input - Use 'Prisfelt_InputParams' to pass parameters into this method.
        /// </summary>
        public void Prisfelt_Input()
        {
            #region Variable Declarations
            WpfEdit uITextBox2Edit = this.UILagerkingWindow.UITextBox2Edit;
            WpfListItem uILagerkingProduktIndeListItem = this.UILagerkingWindow.UILbxAgentsList.UILagerkingProduktIndeListItem;
            #endregion

            // Type '26' in 'textBox2' text box
            uITextBox2Edit.Text = this.Prisfelt_InputParams.UITextBox2EditText;

            // Click 'lagerking.ProduktIndex' list item
            Mouse.Click(uILagerkingProduktIndeListItem, new Point(146, 14));
        }
        
        /// <summary>
        /// AntalFelt_Input - Use 'AntalFelt_InputParams' to pass parameters into this method.
        /// </summary>
        public void AntalFelt_Input()
        {
            #region Variable Declarations
            WpfEdit uITextBox3Edit = this.UILagerkingWindow.UITextBox3Edit;
            WpfListItem uILagerkingProduktIndeListItem = this.UILagerkingWindow.UILbxAgentsList.UILagerkingProduktIndeListItem;
            #endregion

            // Type '300' in 'textBox3' text box
            uITextBox3Edit.Text = this.AntalFelt_InputParams.UITextBox3EditText;

            // Click 'lagerking.ProduktIndex' list item
            Mouse.Click(uILagerkingProduktIndeListItem, new Point(343, 20));
        }
        
        /// <summary>
        /// AfdelingFelt_Input - Use 'AfdelingFelt_InputParams' to pass parameters into this method.
        /// </summary>
        public void AfdelingFelt_Input()
        {
            #region Variable Declarations
            WpfComboBox uIItemComboBox = this.UILagerkingWindow.UIItemComboBox;
            #endregion

            // Select 'A' in combo box
            uIItemComboBox.SelectedItem = this.AfdelingFelt_InputParams.UIItemComboBoxSelectedItem;
        }
        
        /// <summary>
        /// AssertListView_Input - Use 'AssertListView_InputExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertListView_Input()
        {
            #region Variable Declarations
            WpfListItem uILagerkingProduktIndeListItem = this.UILagerkingWindow.UILbxAgentsList.UILagerkingProduktIndeListItem;
            #endregion

            // Verify that the 'DisplayText' property of 'lagerking.ProduktIndex' list item equals 'lagerking.ProduktIndex'
            Assert.AreEqual(this.AssertListView_InputExpectedValues.UILagerkingProduktIndeListItemDisplayText, uILagerkingProduktIndeListItem.DisplayText);
        }
        
        /// <summary>
        /// FeltNavn_Input - Use 'FeltNavn_InputParams' to pass parameters into this method.
        /// </summary>
        public void FeltNavn_Input()
        {
            #region Variable Declarations
            WpfEdit uITbxIdEdit = this.UILagerkingWindow.UITbxIdEdit;
            #endregion

            // Type 'Cola' in 'tbxId' text box
            uITbxIdEdit.Text = this.FeltNavn_InputParams.UITbxIdEditText;
        }
        
        /// <summary>
        /// AssertNavn_IsTrue - Use 'AssertNavn_IsTrueExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertNavn_IsTrue()
        {
            #region Variable Declarations
            WpfEdit uITbxIdEdit = this.UILagerkingWindow.UITbxIdEdit;
            #endregion

            // Verify that the 'Text' property of 'tbxId' text box equals 'Cola'
            Assert.AreEqual(this.AssertNavn_IsTrueExpectedValues.UITbxIdEditText, uITbxIdEdit.Text);
        }
        
        /// <summary>
        /// AssertMethod2 - Use 'AssertMethod2ExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod2()
        {
            #region Variable Declarations
            WpfEdit uITbxIdEdit = this.UILagerkingWindow.UITbxIdEdit;
            #endregion

            // Verify that the 'Text' property of 'tbxId' text box equals 'Cola'
            Assert.AreEqual(this.AssertMethod2ExpectedValues.UITbxIdEditText, uITbxIdEdit.Text);
        }
        
        /// <summary>
        /// NavnInput_Method - Use 'NavnInput_MethodParams' to pass parameters into this method.
        /// </summary>
        public void NavnInput_Method()
        {
            #region Variable Declarations
            WpfEdit uITbxIdEdit = this.UILagerkingWindow.UITbxIdEdit;
            WpfListItem uILagerkingProduktIndeListItem = this.UILagerkingWindow.UILbxAgentsList.UILagerkingProduktIndeListItem;
            #endregion

            // Type 'Cola' in 'tbxId' text box
            uITbxIdEdit.Text = this.NavnInput_MethodParams.UITbxIdEditText;

            // Click 'lagerking.ProduktIndex' list item
            Mouse.Click(uILagerkingProduktIndeListItem, new Point(50, 9));
        }
        
        /// <summary>
        /// AssertMethod3 - Use 'AssertMethod3ExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod3()
        {
            #region Variable Declarations
            WpfEdit uITbxIdEdit = this.UILagerkingWindow.UITbxIdEdit;
            #endregion

            // Verify that the 'Text' property of 'tbxId' text box matches 'Cola'
            StringAssert.Matches(uITbxIdEdit.Text, new Regex(this.AssertMethod3ExpectedValues.UITbxIdEditText));
        }
        
        /// <summary>
        /// AssertMethod4 - Use 'AssertMethod4ExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod4()
        {
            #region Variable Declarations
            WpfListItem uILagerkingProduktIndeListItem = this.UILagerkingWindow.UILbxAgentsList.UILagerkingProduktIndeListItem;
            #endregion

            // Verify that the 'DisplayText' property of 'lagerking.ProduktIndex' list item contains 'lagerking.ProduktIndex'
            StringAssert.Contains(uILagerkingProduktIndeListItem.DisplayText, this.AssertMethod4ExpectedValues.UILagerkingProduktIndeListItemDisplayText);
        }
        
        #region Properties
        public virtual NavnInputParams NavnInputParams
        {
            get
            {
                if ((this.mNavnInputParams == null))
                {
                    this.mNavnInputParams = new NavnInputParams();
                }
                return this.mNavnInputParams;
            }
        }
        
        public virtual PrisInputParams PrisInputParams
        {
            get
            {
                if ((this.mPrisInputParams == null))
                {
                    this.mPrisInputParams = new PrisInputParams();
                }
                return this.mPrisInputParams;
            }
        }
        
        public virtual AntalInputParams AntalInputParams
        {
            get
            {
                if ((this.mAntalInputParams == null))
                {
                    this.mAntalInputParams = new AntalInputParams();
                }
                return this.mAntalInputParams;
            }
        }
        
        public virtual AfdelingInputParams AfdelingInputParams
        {
            get
            {
                if ((this.mAfdelingInputParams == null))
                {
                    this.mAfdelingInputParams = new AfdelingInputParams();
                }
                return this.mAfdelingInputParams;
            }
        }
        
        public virtual AssertListViewInputCorrectExpectedValues AssertListViewInputCorrectExpectedValues
        {
            get
            {
                if ((this.mAssertListViewInputCorrectExpectedValues == null))
                {
                    this.mAssertListViewInputCorrectExpectedValues = new AssertListViewInputCorrectExpectedValues();
                }
                return this.mAssertListViewInputCorrectExpectedValues;
            }
        }
        
        public virtual NavnFieldInputParams NavnFieldInputParams
        {
            get
            {
                if ((this.mNavnFieldInputParams == null))
                {
                    this.mNavnFieldInputParams = new NavnFieldInputParams();
                }
                return this.mNavnFieldInputParams;
            }
        }
        
        public virtual PrisfFieldInputParams PrisfFieldInputParams
        {
            get
            {
                if ((this.mPrisfFieldInputParams == null))
                {
                    this.mPrisfFieldInputParams = new PrisfFieldInputParams();
                }
                return this.mPrisfFieldInputParams;
            }
        }
        
        public virtual AntalFieldInputParams AntalFieldInputParams
        {
            get
            {
                if ((this.mAntalFieldInputParams == null))
                {
                    this.mAntalFieldInputParams = new AntalFieldInputParams();
                }
                return this.mAntalFieldInputParams;
            }
        }
        
        public virtual AfdelingFieldInputParams AfdelingFieldInputParams
        {
            get
            {
                if ((this.mAfdelingFieldInputParams == null))
                {
                    this.mAfdelingFieldInputParams = new AfdelingFieldInputParams();
                }
                return this.mAfdelingFieldInputParams;
            }
        }
        
        public virtual AssertMethod1ExpectedValues AssertMethod1ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod1ExpectedValues == null))
                {
                    this.mAssertMethod1ExpectedValues = new AssertMethod1ExpectedValues();
                }
                return this.mAssertMethod1ExpectedValues;
            }
        }
        
        public virtual AssertNavnInput_TrueExpectedValues AssertNavnInput_TrueExpectedValues
        {
            get
            {
                if ((this.mAssertNavnInput_TrueExpectedValues == null))
                {
                    this.mAssertNavnInput_TrueExpectedValues = new AssertNavnInput_TrueExpectedValues();
                }
                return this.mAssertNavnInput_TrueExpectedValues;
            }
        }
        
        public virtual Navn_InputParams Navn_InputParams
        {
            get
            {
                if ((this.mNavn_InputParams == null))
                {
                    this.mNavn_InputParams = new Navn_InputParams();
                }
                return this.mNavn_InputParams;
            }
        }
        
        public virtual Pris_InputParams Pris_InputParams
        {
            get
            {
                if ((this.mPris_InputParams == null))
                {
                    this.mPris_InputParams = new Pris_InputParams();
                }
                return this.mPris_InputParams;
            }
        }
        
        public virtual Antal_InputParams Antal_InputParams
        {
            get
            {
                if ((this.mAntal_InputParams == null))
                {
                    this.mAntal_InputParams = new Antal_InputParams();
                }
                return this.mAntal_InputParams;
            }
        }
        
        public virtual NavnFelt_InputParams NavnFelt_InputParams
        {
            get
            {
                if ((this.mNavnFelt_InputParams == null))
                {
                    this.mNavnFelt_InputParams = new NavnFelt_InputParams();
                }
                return this.mNavnFelt_InputParams;
            }
        }
        
        public virtual Prisfelt_InputParams Prisfelt_InputParams
        {
            get
            {
                if ((this.mPrisfelt_InputParams == null))
                {
                    this.mPrisfelt_InputParams = new Prisfelt_InputParams();
                }
                return this.mPrisfelt_InputParams;
            }
        }
        
        public virtual AntalFelt_InputParams AntalFelt_InputParams
        {
            get
            {
                if ((this.mAntalFelt_InputParams == null))
                {
                    this.mAntalFelt_InputParams = new AntalFelt_InputParams();
                }
                return this.mAntalFelt_InputParams;
            }
        }
        
        public virtual AfdelingFelt_InputParams AfdelingFelt_InputParams
        {
            get
            {
                if ((this.mAfdelingFelt_InputParams == null))
                {
                    this.mAfdelingFelt_InputParams = new AfdelingFelt_InputParams();
                }
                return this.mAfdelingFelt_InputParams;
            }
        }
        
        public virtual AssertListView_InputExpectedValues AssertListView_InputExpectedValues
        {
            get
            {
                if ((this.mAssertListView_InputExpectedValues == null))
                {
                    this.mAssertListView_InputExpectedValues = new AssertListView_InputExpectedValues();
                }
                return this.mAssertListView_InputExpectedValues;
            }
        }
        
        public virtual FeltNavn_InputParams FeltNavn_InputParams
        {
            get
            {
                if ((this.mFeltNavn_InputParams == null))
                {
                    this.mFeltNavn_InputParams = new FeltNavn_InputParams();
                }
                return this.mFeltNavn_InputParams;
            }
        }
        
        public virtual AssertNavn_IsTrueExpectedValues AssertNavn_IsTrueExpectedValues
        {
            get
            {
                if ((this.mAssertNavn_IsTrueExpectedValues == null))
                {
                    this.mAssertNavn_IsTrueExpectedValues = new AssertNavn_IsTrueExpectedValues();
                }
                return this.mAssertNavn_IsTrueExpectedValues;
            }
        }
        
        public virtual AssertMethod2ExpectedValues AssertMethod2ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod2ExpectedValues == null))
                {
                    this.mAssertMethod2ExpectedValues = new AssertMethod2ExpectedValues();
                }
                return this.mAssertMethod2ExpectedValues;
            }
        }
        
        public virtual NavnInput_MethodParams NavnInput_MethodParams
        {
            get
            {
                if ((this.mNavnInput_MethodParams == null))
                {
                    this.mNavnInput_MethodParams = new NavnInput_MethodParams();
                }
                return this.mNavnInput_MethodParams;
            }
        }
        
        public virtual AssertMethod3ExpectedValues AssertMethod3ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod3ExpectedValues == null))
                {
                    this.mAssertMethod3ExpectedValues = new AssertMethod3ExpectedValues();
                }
                return this.mAssertMethod3ExpectedValues;
            }
        }
        
        public virtual AssertMethod4ExpectedValues AssertMethod4ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod4ExpectedValues == null))
                {
                    this.mAssertMethod4ExpectedValues = new AssertMethod4ExpectedValues();
                }
                return this.mAssertMethod4ExpectedValues;
            }
        }
        
        public UILagerkingWindow UILagerkingWindow
        {
            get
            {
                if ((this.mUILagerkingWindow == null))
                {
                    this.mUILagerkingWindow = new UILagerkingWindow();
                }
                return this.mUILagerkingWindow;
            }
        }
        #endregion
        
        #region Fields
        private NavnInputParams mNavnInputParams;
        
        private PrisInputParams mPrisInputParams;
        
        private AntalInputParams mAntalInputParams;
        
        private AfdelingInputParams mAfdelingInputParams;
        
        private AssertListViewInputCorrectExpectedValues mAssertListViewInputCorrectExpectedValues;
        
        private NavnFieldInputParams mNavnFieldInputParams;
        
        private PrisfFieldInputParams mPrisfFieldInputParams;
        
        private AntalFieldInputParams mAntalFieldInputParams;
        
        private AfdelingFieldInputParams mAfdelingFieldInputParams;
        
        private AssertMethod1ExpectedValues mAssertMethod1ExpectedValues;
        
        private AssertNavnInput_TrueExpectedValues mAssertNavnInput_TrueExpectedValues;
        
        private Navn_InputParams mNavn_InputParams;
        
        private Pris_InputParams mPris_InputParams;
        
        private Antal_InputParams mAntal_InputParams;
        
        private NavnFelt_InputParams mNavnFelt_InputParams;
        
        private Prisfelt_InputParams mPrisfelt_InputParams;
        
        private AntalFelt_InputParams mAntalFelt_InputParams;
        
        private AfdelingFelt_InputParams mAfdelingFelt_InputParams;
        
        private AssertListView_InputExpectedValues mAssertListView_InputExpectedValues;
        
        private FeltNavn_InputParams mFeltNavn_InputParams;
        
        private AssertNavn_IsTrueExpectedValues mAssertNavn_IsTrueExpectedValues;
        
        private AssertMethod2ExpectedValues mAssertMethod2ExpectedValues;
        
        private NavnInput_MethodParams mNavnInput_MethodParams;
        
        private AssertMethod3ExpectedValues mAssertMethod3ExpectedValues;
        
        private AssertMethod4ExpectedValues mAssertMethod4ExpectedValues;
        
        private UILagerkingWindow mUILagerkingWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'NavnInput'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class NavnInputParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Cola' in 'tbxId' text box
        /// </summary>
        public string UITbxIdEditText = "Cola";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'PrisInput'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class PrisInputParams
    {
        
        #region Fields
        /// <summary>
        /// Type '25' in 'textBox2' text box
        /// </summary>
        public string UITextBox2EditText = "25";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AntalInput'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class AntalInputParams
    {
        
        #region Fields
        /// <summary>
        /// Type '2' in 'textBox3' text box
        /// </summary>
        public string UITextBox3EditText = "2";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AfdelingInput'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class AfdelingInputParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'D' in combo box
        /// </summary>
        public string UIItemComboBoxSelectedItem = "D";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertListViewInputCorrect'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class AssertListViewInputCorrectExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'DisplayText' property of 'lagerking.ProduktIndex' list item equals 'lagerking.ProduktIndex'
        /// </summary>
        public string UILagerkingProduktIndeListItemDisplayText = "lagerking.ProduktIndex";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'NavnFieldInput'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class NavnFieldInputParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Cola' in 'tbxId' text box
        /// </summary>
        public string UITbxIdEditText = "Cola";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'PrisfFieldInput'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class PrisfFieldInputParams
    {
        
        #region Fields
        /// <summary>
        /// Type '15' in 'textBox2' text box
        /// </summary>
        public string UITextBox2EditText = "15";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AntalFieldInput'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class AntalFieldInputParams
    {
        
        #region Fields
        /// <summary>
        /// Type '300' in 'textBox3' text box
        /// </summary>
        public string UITextBox3EditText = "300";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AfdelingFieldInput'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class AfdelingFieldInputParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'B' in combo box
        /// </summary>
        public string UIItemComboBoxSelectedItem = "B";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class AssertMethod1ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'DisplayText' property of 'lagerking.ProduktIndex' list item equals 'lagerking.ProduktIndex'
        /// </summary>
        public string UILagerkingProduktIndeListItemDisplayText = "lagerking.ProduktIndex";
        
        /// <summary>
        /// Verify that the 'DisplayText' property of 'lagerking.ProduktIndex' list item equals 'lagerking.ProduktIndex'
        /// </summary>
        public string UILagerkingProduktIndeListItemDisplayText1 = "lagerking.ProduktIndex";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertNavnInput_True'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class AssertNavnInput_TrueExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'tbxId' text box equals 'Cola'
        /// </summary>
        public string UITbxIdEditText = "Cola";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Navn_Input'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class Navn_InputParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Honning' in 'tbxId' text box
        /// </summary>
        public string UITbxIdEditText = "Honning";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Pris_Input'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class Pris_InputParams
    {
        
        #region Fields
        /// <summary>
        /// Type '26' in 'textBox2' text box
        /// </summary>
        public string UITextBox2EditText = "26";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Antal_Input'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class Antal_InputParams
    {
        
        #region Fields
        /// <summary>
        /// Type '340' in 'textBox3' text box
        /// </summary>
        public string UITextBox3EditText = "340";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'NavnFelt_Input'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class NavnFelt_InputParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Honning' in 'tbxId' text box
        /// </summary>
        public string UITbxIdEditText = "Honning";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Prisfelt_Input'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class Prisfelt_InputParams
    {
        
        #region Fields
        /// <summary>
        /// Type '26' in 'textBox2' text box
        /// </summary>
        public string UITextBox2EditText = "26";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AntalFelt_Input'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class AntalFelt_InputParams
    {
        
        #region Fields
        /// <summary>
        /// Type '300' in 'textBox3' text box
        /// </summary>
        public string UITextBox3EditText = "300";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AfdelingFelt_Input'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class AfdelingFelt_InputParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'A' in combo box
        /// </summary>
        public string UIItemComboBoxSelectedItem = "A";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertListView_Input'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class AssertListView_InputExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'DisplayText' property of 'lagerking.ProduktIndex' list item equals 'lagerking.ProduktIndex'
        /// </summary>
        public string UILagerkingProduktIndeListItemDisplayText = "lagerking.ProduktIndex";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'FeltNavn_Input'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class FeltNavn_InputParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Cola' in 'tbxId' text box
        /// </summary>
        public string UITbxIdEditText = "Cola";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertNavn_IsTrue'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class AssertNavn_IsTrueExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'tbxId' text box equals 'Cola'
        /// </summary>
        public string UITbxIdEditText = "Cola";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class AssertMethod2ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'tbxId' text box equals 'Cola'
        /// </summary>
        public string UITbxIdEditText = "Cola";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'NavnInput_Method'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class NavnInput_MethodParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Cola' in 'tbxId' text box
        /// </summary>
        public string UITbxIdEditText = "Cola";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod3'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class AssertMethod3ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'tbxId' text box matches 'Cola'
        /// </summary>
        public string UITbxIdEditText = "Cola";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod4'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class AssertMethod4ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'DisplayText' property of 'lagerking.ProduktIndex' list item contains 'lagerking.ProduktIndex'
        /// </summary>
        public string UILagerkingProduktIndeListItemDisplayText = "lagerking.ProduktIndex";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UILagerkingWindow : WpfWindow
    {
        
        public UILagerkingWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Lagerking";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Lagerking");
            #endregion
        }
        
        #region Properties
        public WpfEdit UITbxIdEdit
        {
            get
            {
                if ((this.mUITbxIdEdit == null))
                {
                    this.mUITbxIdEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITbxIdEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "tbxId";
                    this.mUITbxIdEdit.WindowTitles.Add("Lagerking");
                    #endregion
                }
                return this.mUITbxIdEdit;
            }
        }
        
        public WpfEdit UITextBox2Edit
        {
            get
            {
                if ((this.mUITextBox2Edit == null))
                {
                    this.mUITextBox2Edit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITextBox2Edit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "textBox2";
                    this.mUITextBox2Edit.WindowTitles.Add("Lagerking");
                    #endregion
                }
                return this.mUITextBox2Edit;
            }
        }
        
        public WpfEdit UITextBox3Edit
        {
            get
            {
                if ((this.mUITextBox3Edit == null))
                {
                    this.mUITextBox3Edit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITextBox3Edit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "textBox3";
                    this.mUITextBox3Edit.WindowTitles.Add("Lagerking");
                    #endregion
                }
                return this.mUITextBox3Edit;
            }
        }
        
        public WpfComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIItemComboBox.WindowTitles.Add("Lagerking");
                    #endregion
                }
                return this.mUIItemComboBox;
            }
        }
        
        public UILbxAgentsList UILbxAgentsList
        {
            get
            {
                if ((this.mUILbxAgentsList == null))
                {
                    this.mUILbxAgentsList = new UILbxAgentsList(this);
                }
                return this.mUILbxAgentsList;
            }
        }
        
        public UIItemToolBar UIItemToolBar
        {
            get
            {
                if ((this.mUIItemToolBar == null))
                {
                    this.mUIItemToolBar = new UIItemToolBar(this);
                }
                return this.mUIItemToolBar;
            }
        }
        
        public WpfButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "button1";
                    this.mUILoginButton.WindowTitles.Add("Lagerking");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUITbxIdEdit;
        
        private WpfEdit mUITextBox2Edit;
        
        private WpfEdit mUITextBox3Edit;
        
        private WpfComboBox mUIItemComboBox;
        
        private UILbxAgentsList mUILbxAgentsList;
        
        private UIItemToolBar mUIItemToolBar;
        
        private WpfButton mUILoginButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UILbxAgentsList : WpfList
    {
        
        public UILbxAgentsList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfList.PropertyNames.AutomationId] = "lbxAgents";
            this.WindowTitles.Add("Lagerking");
            #endregion
        }
        
        #region Properties
        public WpfListItem UILagerkingProduktIndeListItem
        {
            get
            {
                if ((this.mUILagerkingProduktIndeListItem == null))
                {
                    this.mUILagerkingProduktIndeListItem = new WpfListItem(this);
                    #region Search Criteria
                    this.mUILagerkingProduktIndeListItem.SearchProperties[WpfListItem.PropertyNames.Name] = "lagerking.ProduktIndex";
                    this.mUILagerkingProduktIndeListItem.WindowTitles.Add("Lagerking");
                    #endregion
                }
                return this.mUILagerkingProduktIndeListItem;
            }
        }
        #endregion
        
        #region Fields
        private WpfListItem mUILagerkingProduktIndeListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.28315.86")]
    public class UIItemToolBar : WpfToolBar
    {
        
        public UIItemToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Lagerking");
            #endregion
        }
        
        #region Properties
        public WpfButton UITilføjvareButton
        {
            get
            {
                if ((this.mUITilføjvareButton == null))
                {
                    this.mUITilføjvareButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUITilføjvareButton.SearchProperties[WpfButton.PropertyNames.HelpText] = "Tilføj vare";
                    this.mUITilføjvareButton.WindowTitles.Add("Lagerking");
                    #endregion
                }
                return this.mUITilføjvareButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUITilføjvareButton;
        #endregion
    }
}
