// <auto-generated />
namespace lagerking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class department : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(department));
        
        string IMigrationMetadata.Id
        {
            get { return "201905251204042_department"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
